### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by A5rocks**
The code doesn't look very inviting, so might as well make it prettier.

### CODE REVIEW

**Comment by A5rocks** [comment]
Hope I'm not messing anything up with my next commit!

**Comment by A5rocks** [comment]
Okay, now we just need to write the commands in `commands.py`. At least, that's what I think.

**Comment by AllAwesome497** [comment]
yes. in the file of their catagory
also- that stuff in on_ready stuff is for testing purposes, and for resetting the keys when i had incorrect data in them.

**Comment by AllAwesome497** [comment]
Closed because branch is inactive

**Pull request closed without merging**
